name: nxt
base: core24
version: '0.1.0'
summary: High performance WAMP router based on xconn-go
description: |
  High performance WAMP router based on xconn-go

grade: stable
confinement: strict

apps:
  nxt:
    command: bin/nxt
    completer: bash_autocomplete.sh
    plugs:
      - network
      - network-bind
      - home

parts:
  nxt:
    plugin: go
    source: .
    build-snaps:
      - go
    override-prime: |
      craftctl default
      cp $CRAFT_PART_SRC/bash_autocomplete.sh $CRAFT_PRIME/
